// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +xsmtvdot \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>
#pragma clang riscv intrinsic spacemit_vector

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_smt_vmadot(
// CHECK-RV64-SAME: <vscale x 4 x i32> [[VD:%.*]], <vscale x 8 x i8> [[VS1:%.*]], <vscale x 8 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  [[ENTRY:.*:]]
// CHECK-RV64-NEXT:    [[VD_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-RV64-NEXT:    [[VS1_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VS2_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VL_ADDR:%.*]] = alloca i64, align 8
// CHECK-RV64-NEXT:    store <vscale x 4 x i32> [[VD]], ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS1]], ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS2]], ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    store i64 [[VL]], ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i8>, ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP2:%.*]] = load <vscale x 8 x i8>, ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP3:%.*]] = load i64, ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.riscv.smt.vmadot.nxv4i32.nxv8i8.nxv8i8.i64(<vscale x 4 x i32> [[TMP0]], <vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8> [[TMP2]], i64 [[TMP3]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP4]]
//
vint32m2_t test_smt_vmadot(vint32m2_t vd, vint8m1_t vs1, vint8m1_t vs2, size_t vl) {
  return __riscv_smt_vmadot(vd, vs1, vs2, vl);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_smt_vmadotu(
// CHECK-RV64-SAME: <vscale x 4 x i32> [[VD:%.*]], <vscale x 8 x i8> [[VS1:%.*]], <vscale x 8 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  [[ENTRY:.*:]]
// CHECK-RV64-NEXT:    [[VD_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-RV64-NEXT:    [[VS1_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VS2_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VL_ADDR:%.*]] = alloca i64, align 8
// CHECK-RV64-NEXT:    store <vscale x 4 x i32> [[VD]], ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS1]], ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS2]], ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    store i64 [[VL]], ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i8>, ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP2:%.*]] = load <vscale x 8 x i8>, ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP3:%.*]] = load i64, ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.riscv.smt.vmadotu.nxv4i32.nxv8i8.nxv8i8.i64(<vscale x 4 x i32> [[TMP0]], <vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8> [[TMP2]], i64 [[TMP3]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP4]]
//
vint32m2_t test_smt_vmadotu(vint32m2_t vd, vuint8m1_t vs1, vuint8m1_t vs2, size_t vl) {
  return __riscv_smt_vmadotu(vd, vs1, vs2, vl);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_smt_vmadotsu(
// CHECK-RV64-SAME: <vscale x 4 x i32> [[VD:%.*]], <vscale x 8 x i8> [[VS1:%.*]], <vscale x 8 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  [[ENTRY:.*:]]
// CHECK-RV64-NEXT:    [[VD_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-RV64-NEXT:    [[VS1_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VS2_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VL_ADDR:%.*]] = alloca i64, align 8
// CHECK-RV64-NEXT:    store <vscale x 4 x i32> [[VD]], ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS1]], ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS2]], ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    store i64 [[VL]], ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i8>, ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP2:%.*]] = load <vscale x 8 x i8>, ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP3:%.*]] = load i64, ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.riscv.smt.vmadotsu.nxv4i32.nxv8i8.nxv8i8.i64(<vscale x 4 x i32> [[TMP0]], <vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8> [[TMP2]], i64 [[TMP3]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP4]]
//
vint32m2_t test_smt_vmadotsu(vint32m2_t vd, vint8m1_t vs1, vuint8m1_t vs2, size_t vl) {
  return __riscv_smt_vmadotsu(vd, vs1, vs2, vl);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_smt_vmadotus(
// CHECK-RV64-SAME: <vscale x 4 x i32> [[VD:%.*]], <vscale x 8 x i8> [[VS1:%.*]], <vscale x 8 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  [[ENTRY:.*:]]
// CHECK-RV64-NEXT:    [[VD_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-RV64-NEXT:    [[VS1_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VS2_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-RV64-NEXT:    [[VL_ADDR:%.*]] = alloca i64, align 8
// CHECK-RV64-NEXT:    store <vscale x 4 x i32> [[VD]], ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS1]], ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    store <vscale x 8 x i8> [[VS2]], ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    store i64 [[VL]], ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, ptr [[VD_ADDR]], align 4
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i8>, ptr [[VS1_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP2:%.*]] = load <vscale x 8 x i8>, ptr [[VS2_ADDR]], align 1
// CHECK-RV64-NEXT:    [[TMP3:%.*]] = load i64, ptr [[VL_ADDR]], align 8
// CHECK-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.riscv.smt.vmadotus.nxv4i32.nxv8i8.nxv8i8.i64(<vscale x 4 x i32> [[TMP0]], <vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8> [[TMP2]], i64 [[TMP3]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP4]]
//
vint32m2_t test_smt_vmadotus(vint32m2_t vd, vuint8m1_t vs1, vint8m1_t vs2, size_t vl) {
  return __riscv_smt_vmadotus(vd, vs1, vs2, vl);
}
